In [66]:
import gym
import numpy as np
import time
import random
from IPython.display import clear_output
env = gym.make('FrozenLake-v1')


In [67]:
colunas_açoes = env.action_space.n
linhas_estados = env.observation_space.n

tabela_q = np.zeros((linhas_estados, colunas_açoes))
print(tabela_q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [76]:
todas_recompensas = []

num_episodios = 10000
num_passos_por_episodio = 100

taxa_de_aprendizado = 0.1
taxa_de_desconto = 0.99

taxa_exploration = 1
max_taxa_exploration = 1
min_taxa_exploration = 0.01
taxa_de_decaimento_da_exploração = 0.001




  #Q-learning algoritimo
  #primeiro for contem tudo o que acontece em um unico episodio
for episodio in range(num_episodios):
  estado = env.reset()
  done = False
  recompensas_episodio_atual = 0
   #segundo for contem tudo o que acontece em um intervalo dos episodios episodios
  for passo in range(num_passos_por_episodio):
    #exploration - exploitation (Trade-off)
    limite_taxa_exploration = random.uniform(0, 1)

    if limite_taxa_exploration > taxa_exploration_epilson:
      action = np.argmax(tabela_q[estado,:])

    else:
        action = env.action_space.sample()

    #new_state, reward, done, info = env.step(action)
    novo_estado, recompensa, done, info  = env.step(action)

    #atualização da tabela Q
    tabela_q[estado, action] = tabela_q[estado, action] * (1 - taxa_de_aprendizado) + \
      taxa_de_aprendizado *(recompensa + taxa_de_desconto *np.max(tabela_q[novo_estado,:]))

    estado = novo_estado
    recompensas_episodio_atual += recompensa

    if done == True:
      break


      #taxa de decaimento de exploração
    taxa_exploration = min_taxa_exploration + \
    (max_taxa_exploration - min_taxa_exploration) * np.exp(-taxa_de_decaimento_da_exploração * episodio)

    todas_recompensas.append(recompensas_episodio_atual)

#calcular a recompensa media de um total de 1000 episodios
media_total_recompensas = np.array_split(np.array(todas_recompensas),num_episodios/1000)
count = 1000


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [77]:
print("RECOMPENSA MEDIA DE TODOS OS EPISODIOS:")
for r in media_total_recompensas:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

#print atualização da tabela Q
print("\n\n********TABELA_Q********\n")
print(tabela_q)

RECOMPENSA MEDIA DE TODOS OS EPISODIOS:
1000 :  0.0
2000 :  0.0
3000 :  0.0
4000 :  0.0
5000 :  0.0
6000 :  0.0
7000 :  0.0
8000 :  0.0
9000 :  0.0
10000 :  0.0


********TABELA_Q********

[[0.49260643 0.48615945 0.48231157 0.47429892]
 [0.29833063 0.3813374  0.25929804 0.45833208]
 [0.43996814 0.43827941 0.43388936 0.45536078]
 [0.23159925 0.27165119 0.3381453  0.45459809]
 [0.50323185 0.40087396 0.38688589 0.33145924]
 [0.         0.         0.         0.        ]
 [0.37896374 0.19317015 0.41374772 0.10070413]
 [0.         0.         0.         0.        ]
 [0.30539094 0.31049712 0.25382793 0.54891992]
 [0.471916   0.5981161  0.36089614 0.28801542]
 [0.57402458 0.53485211 0.35831705 0.31718365]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.40409507 0.55631676 0.71961496 0.40520944]
 [0.73107678 0.85518911 0.82210774 0.71845686]
 [0.         0.         0.         0.        ]]
